# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/Azure/go-ansiterm"

[[constraint]]
  branch = "master"
  name = "github.com/alexcesaro/log"

[[constraint]]
  branch = "master"
  name = "github.com/apex/log"

[[constraint]]
  branch = "master"
  name = "github.com/armon/go-socks5"

[[constraint]]
  branch = "master"
  name = "github.com/codegangsta/cli"

[[constraint]]
  name = "github.com/fatedier/frp"
  version = "0.16.1"

[[constraint]]
  branch = "master"
  name = "github.com/gostones/ssh-chat"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  branch = "master"
  name = "github.com/jessevdk/go-flags"

[[constraint]]
  name = "github.com/jpillora/chisel"
  version = "1.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/jpillora/requestlog"

[[constraint]]
  branch = "master"
  name = "github.com/jpillora/sizestr"

[[constraint]]
  name = "github.com/kr/pty"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/moul/ssh2docker"

[[constraint]]
  branch = "master"
  name = "github.com/shirou/gopsutil"

[[constraint]]
  branch = "master"
  name = "github.com/vaughan0/go-ini"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.3.0"

[prune]
  go-tests = true
  unused-packages = true
